// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLFhS7779ZWgMVLJdTqxTn3LmrTEWp_Rs',
    appId: '1:243784905645:web:bb399d75a389d749036724',
    messagingSenderId: '243784905645',
    projectId: 'chatapp-46d09',
    authDomain: 'chatapp-46d09.firebaseapp.com',
    storageBucket: 'chatapp-46d09.appspot.com',
    measurementId: 'G-2EV0KFG0Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOGV5w1YXmA3QxdXjIlPnyK-AWm9IM1FM',
    appId: '1:243784905645:android:c67f0c194abc45f1036724',
    messagingSenderId: '243784905645',
    projectId: 'chatapp-46d09',
    storageBucket: 'chatapp-46d09.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARPzvUFB95fX96-vx0HV1RdeDPqNhTB-w',
    appId: '1:243784905645:ios:bc4c3683400234da036724',
    messagingSenderId: '243784905645',
    projectId: 'chatapp-46d09',
    storageBucket: 'chatapp-46d09.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARPzvUFB95fX96-vx0HV1RdeDPqNhTB-w',
    appId: '1:243784905645:ios:bc4c3683400234da036724',
    messagingSenderId: '243784905645',
    projectId: 'chatapp-46d09',
    storageBucket: 'chatapp-46d09.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLFhS7779ZWgMVLJdTqxTn3LmrTEWp_Rs',
    appId: '1:243784905645:web:e77b57d59739e953036724',
    messagingSenderId: '243784905645',
    projectId: 'chatapp-46d09',
    authDomain: 'chatapp-46d09.firebaseapp.com',
    storageBucket: 'chatapp-46d09.appspot.com',
    measurementId: 'G-Z0WH06C7DT',
  );
}
